ASP/Controllers/RouteController.cs
using ASP.Models;
using DAL.DAL;
using Logic.Containers;
using Logic.Models;
using Microsoft.AspNetCore.Mvc;

namespace ASP.Controllers
{
    public class RouteController : Controller
    {
        private readonly ILogger<RouteController> _logger;

        public RouteController(ILogger<RouteController> logger)
        {
            _logger = logger;
        }
        private List<WerknemerViewModel> GetWerknemers()
        {
            WerknemerContainer werknemerContainer = new WerknemerContainer(new WerknemerDAL());
            List<WerknemerViewModel> werknemerViewModels = new List<WerknemerViewModel>();
            foreach (var werknemer in werknemerContainer.GetUserWerknemers(HttpContext.Session.GetInt32("user-id").Value))
            {
                WerknemerViewModel werknemerViewModel = new WerknemerViewModel
                {
                    WerknemerID = werknemer.WerknemerID,
                    Naam = werknemer.Naam,
                    WerknemerNummer = werknemer.WerknemerNummer,
                    TelefoonNummer = werknemer.TelefoonNummer
                };
                werknemerViewModels.Add(werknemerViewModel);
            }
            return werknemerViewModels;
        }

        private List<RouteViewModel> GetRoutes()
        {
            RouteContainer routeContainer = new RouteContainer(new RouteDAL());
            List<RouteViewModel> routeViewModels = new List<RouteViewModel>();
            foreach (var routes in routeContainer.GetRoutes(new WerknemerDAL(), new WerknemerDAL(), HttpContext.Session.GetInt32("user-id").Value))
            {
                RouteViewModel routeViewModel = new RouteViewModel
                {
                    RouteID = routes.RouteID,
                    RouteNummer = routes.RouteNummer,
                    Datum = routes.Datum,
                    Chauffeur = routes.Chauffeur,
                    BijRijder = routes.BijRijder,
                    StartTijd = routes.StartTijd,
                    EindTijd = routes.EindTijd,
                    AantalUur = routes.AantalUur,
                    Bijzonderheden = routes.Bijzonderheden
                };
                routeViewModels.Add(routeViewModel);
            }
            return routeViewModels;
        }

        [HttpPost]
        public ActionResult GetRoutesFromDate(string date)
        {
            RouteContainer routeContainer = new RouteContainer(new RouteDAL());
            List<RouteViewModel> routeViewModels = new List<RouteViewModel>();
            foreach (var routes in routeContainer.GetRoutesFromDate(date, new WerknemerDAL(), new WerknemerDAL(), HttpContext.Session.GetInt32("user-id").Value))
            {
                RouteViewModel routeViewModel = new RouteViewModel
                {
                    RouteID = routes.RouteID,
                    RouteNummer = routes.RouteNummer,
                    Datum = routes.Datum,
                    Chauffeur = routes.Chauffeur,
                    BijRijder = routes.BijRijder,
                    StartTijd = routes.StartTijd,
                    EindTijd = routes.EindTijd,
                    AantalUur = routes.AantalUur,
                    Bijzonderheden = routes.Bijzonderheden
                };
                routeViewModels.Add(routeViewModel);
            }
            return Ok(routeViewModels);
        }

        [HttpGet]
        public IActionResult RouteToevoegenView()
        {
            ViewData["Routes"] = GetRoutes();
            ViewData["Werknemers"] = GetWerknemers();
            return View();
        }

        [HttpPost]
        public ActionResult RouteToevoegen(int routeNummer, string rawDatum, int chauffeurID, int bijrijderID, string rawStartTijd, string rawEindTijd, string bijzonderheden)
        {
            DateTime parsedDatum;
            TimeSpan parsedStartTijd;
            TimeSpan parsedEindTijd;

            WerknemerContainer werknemerContainer = new WerknemerContainer(new WerknemerDAL());
            Werknemer chauffeur = werknemerContainer.GetUserWerknemers(HttpContext.Session.GetInt32("user-id").Value).FirstOrDefault(w => w.WerknemerID == chauffeurID);
            Werknemer bijrijder = werknemerContainer.GetUserWerknemers(HttpContext.Session.GetInt32("user-id").Value).FirstOrDefault(w => w.WerknemerID == bijrijderID);


            DateTime.TryParse(rawDatum, out parsedDatum);
            TimeSpan.TryParse(rawStartTijd, out parsedStartTijd);
            TimeSpan.TryParse(rawEindTijd, out parsedEindTijd);

            RouteRit newRoute = new RouteRit(routeNummer, parsedDatum, chauffeur, bijrijder, parsedStartTijd, parsedEindTijd, bijzonderheden, new RouteDAL());
            newRoute.AddRoute(HttpContext.Session.GetInt32("user-id").Value);
            return Ok("Route Toegevoegd");
        }

        [HttpGet]
        public IActionResult RouteAanpassenView()
        {
            ViewData["Werknemers"] = GetWerknemers();
            return View();
        }   

        [HttpPost]
        public ActionResult RouteAanpassen(int routeId, int routeNummer, string rawDatum, int chauffeurID, int bijrijderID, string rawStartTijd, string rawEindTijd, string bijzonderheden)
        {
            DateTime parsedDatum;
            TimeSpan parsedStartTijd;
            TimeSpan parsedEindTijd;

            WerknemerContainer werknemerContainer = new WerknemerContainer(new WerknemerDAL());
            Werknemer chauffeur = werknemerContainer.GetUserWerknemers(HttpContext.Session.GetInt32("user-id").Value).FirstOrDefault(w => w.WerknemerID == chauffeurID);
            Werknemer bijrijder = werknemerContainer.GetUserWerknemers(HttpContext.Session.GetInt32("user-id").Value).FirstOrDefault(w => w.WerknemerID == bijrijderID);


            DateTime.TryParse(rawDatum, out parsedDatum);
            TimeSpan.TryParse(rawStartTijd, out parsedStartTijd);
            TimeSpan.TryParse(rawEindTijd, out parsedEindTijd);

            RouteRit newRoute = new RouteRit(routeId, routeNummer, parsedDatum, chauffeur, bijrijder, parsedStartTijd, parsedEindTijd, bijzonderheden, new RouteDAL());
            newRoute.UpdateRoute();
            return Ok("Route Aangepast");
        }

        [HttpPost]
        public ActionResult GetSingleRouteByID(int id)
        {
            RouteContainer routeContainer = new RouteContainer(new RouteDAL());
            RouteRit routeRit = routeContainer.GetSingleRoute(HttpContext.Session.GetInt32("user-id").Value, id, new WerknemerDAL(), new WerknemerDAL());
            RouteViewModel route = new RouteViewModel()
            {
                RouteID = routeRit.RouteID,
                RouteNummer = routeRit.RouteNummer,
                Datum = routeRit.Datum,
                Chauffeur = routeRit.Chauffeur,
                BijRijder = routeRit.BijRijder,
                StartTijd = routeRit.StartTijd,
                EindTijd = routeRit.EindTijd,
                AantalUur = routeRit.AantalUur,
                Bijzonderheden = routeRit.Bijzonderheden
            };

            return Ok(route);
        }

        [HttpGet]
        public IActionResult RouteVerwijderenView()
        {
            return View();
        }

        [HttpPost]
        public ActionResult RouteVerwijderen(int id)
        {
            RouteContainer routeContainer = new RouteContainer(new RouteDAL());
            RouteRit route = routeContainer.GetRoutes(new WerknemerDAL(), new WerknemerDAL(),HttpContext.Session.GetInt32("user-id").Value).FirstOrDefault(r => r.RouteID == id);

            route.DeleteRoute();
            return Ok("Route Verwijderd");
        }

        [HttpPost]
        public ActionResult GetMonthConclusion(string chosenMonth)
        {
            MonthConclusionContainer monthConclusionContainer = new MonthConclusionContainer(new MonthConclusionDAL());

            MonthConclusion monthConclusion = monthConclusionContainer.CalcMonthConclusion(chosenMonth, new WerknemerDAL(), new WerknemerDAL(), HttpContext.Session.GetInt32("user-id").Value, new RouteDAL());

            return Ok(monthConclusion);
        }
    }
}

ASP/Controllers/WerknemerController.cs
using ASP.Models;
using DAL.DAL;
using Logic.Containers;
using Logic.Models;
using Microsoft.AspNetCore.Mvc;

namespace ASP.Controllers
{
    public class WerknemerController : Controller
    {
        private readonly ILogger<WerknemerController> _logger;

        public WerknemerController(ILogger<WerknemerController> logger)
        {
            _logger = logger;
        }

        private List<WerknemerViewModel> GetUserWerknemers()
        {
            WerknemerContainer werknemerContainer = new WerknemerContainer(new WerknemerDAL());
            List<WerknemerViewModel> werknemerViewModels = new List<WerknemerViewModel>();
            foreach (Werknemer werknemer in werknemerContainer.GetUserWerknemers(HttpContext.Session.GetInt32("user-id").Value))
            {
                WerknemerViewModel werknemerViewModel = new WerknemerViewModel
                {
                    WerknemerID = werknemer.WerknemerID,
                    Naam = werknemer.Naam,
                    WerknemerNummer = werknemer.WerknemerNummer,
                    TelefoonNummer = werknemer.TelefoonNummer
                };
                werknemerViewModels.Add(werknemerViewModel);
            }
            return werknemerViewModels;
        }

        private List<WerknemerViewModel> GetAllWerknemers()
        {
            WerknemerContainer werknemerContainer = new WerknemerContainer(new WerknemerDAL());
            List<WerknemerViewModel> werknemerViewModels = new List<WerknemerViewModel>();
            foreach (Werknemer werknemer in werknemerContainer.GetAllWerknemers())
            {
                WerknemerViewModel werknemerViewModel = new WerknemerViewModel
                {
                    WerknemerID = werknemer.WerknemerID,
                    Naam = werknemer.Naam,
                    WerknemerNummer = werknemer.WerknemerNummer,
                    TelefoonNummer = werknemer.TelefoonNummer
                };
                werknemerViewModels.Add(werknemerViewModel);
            }
            return werknemerViewModels;
        }

        [HttpGet]
        public IActionResult WerknemerToevoegenView()
        {
            ViewData["Werknemers"] = GetAllWerknemers();
            return View();
        }

        [HttpGet]
        public IActionResult WerknemerAanpassenView()
        {
            return View(GetUserWerknemers());
        }

        [HttpGet]
        public IActionResult WerknemerVerwijderenView()
        {
            return View(GetUserWerknemers());
        }

        [HttpPost]
        public ActionResult WerknemerToevoegen(WerknemerViewModel werknemerViewModel) 
        {
            if (ModelState.IsValid)
            {
                Werknemer werknemer = new Werknemer(werknemerViewModel.Naam, werknemerViewModel.WerknemerNummer, werknemerViewModel.TelefoonNummer, new WerknemerDAL());
                werknemer.AddWerknemer(HttpContext.Session.GetInt32("user-id").Value);
                return RedirectToAction("Index", "Home");
            }
            else
                return BadRequest();
        }

        [HttpPost]
        public ActionResult WerknemerAanpassen(string newNaam, int newWerknemerNum, int newTelefoonNum, int oldWerknemerID)
        {
            Werknemer werknemer = new Werknemer(newNaam, newWerknemerNum, newTelefoonNum, new WerknemerDAL());
            werknemer.UpdateWerknemer(oldWerknemerID);
            return Ok("Werknemer aangepast");
        }

        [HttpPost]
        public ActionResult WerknemerVerwijderen(int id)
        {
            Werknemer werknemer = new Werknemer(new WerknemerDAL());
            werknemer.WerknemerID = id;
            werknemer.DeleteWerknemer();
            return Ok("Werknemer verwijderd");
        }

        [HttpPost]
        public ActionResult<Werknemer> LoadWerknemer(int id)
        {
            WerknemerContainer werknemerContainer = new WerknemerContainer(new WerknemerDAL());
            Werknemer output = werknemerContainer.GetSingleWerknemer(id);

            if (output == null)
            {
                return Conflict("Geen werknemer gevonden");
            }

            return Ok(output);
        }

        [HttpPost]
        public ActionResult LinkWerknemerToUser(int ID)
        {
            Werknemer werknemer = new Werknemer(new WerknemerDAL())
            {
                WerknemerID = ID
            };

            if (werknemer.LinkWerknemerToUser(HttpContext.Session.GetInt32("user-id").Value) == 1)
            {
                return Ok("Succesvol Gelinkt");
            }
            return BadRequest("Fout");
        }
    }
}

ASP/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AdmiNote</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ASP.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
</head>
<body>
    <nav class="navbar navbar-icon-top navbar-expand-lg navbar-dark shadow">
        <a class="navbar-brand mx-3" asp-controller="Home" asp-action="Index">AdmiNote</a>

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <div class="navbar-collapse collapse d-sm-inline-flex">
                <ul class="navbar-nav flex-grow-1">
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" id="routedropdown" role="button" data-bs-toggle="dropdown">
                                        Werknemer
                                    </a>

                                    <div class="dropdown-menu" aria-labelledby="routedropdown">
                                         <a class="dropdown-item" asp-controller="Werknemer" asp-action="WerknemerToevoegenView">Werknemer Toevoegen</a>
                                         <a class="dropdown-item" asp-controller="Werknemer" asp-action="WerknemerAanpassenView">Werknemer Aanpassen</a>
                                         <a class="dropdown-item" asp-controller="Werknemer" asp-action="WerknemerVerwijderenView">Werknemer Verwijderen</a>
                                    </div>
                                </li>

                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" id="routedropdown" role="button" data-bs-toggle="dropdown">
                                        Route
                                    </a>

                                    <div class="dropdown-menu" aria-labelledby="routedropdown">
                                         <a class="dropdown-item" asp-controller="Route" asp-action="RouteToevoegenView">Route Toevoegen</a>
                                         <a class="dropdown-item" asp-controller="Route" asp-action="RouteAanpassenView">Route Aanpassen</a>
                                         <a class="dropdown-item" asp-controller="Route" asp-action="RouteVerwijderenView">Route Verwijderen</a>
                                    </div>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="Home" asp-action="MonthConclusion">Maand Gegevens</a>
                                </li>

                            </ul>
                            <button type="button" class="btn btn-danger mx-4" onclick="logout()">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-box-arrow-right" viewBox="0 0 16 16">
                                    <path fill-rule="evenodd" d="M10 12.5a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v2a.5.5 0 0 0 1 0v-2A1.5 1.5 0 0 0 9.5 2h-8A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-2a.5.5 0 0 0-1 0v2z"></path>
                                    <path fill-rule="evenodd" d="M15.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 0 0-.708.708L14.293 7.5H5.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3z"></path>
                                </svg>
                                Log Out
                            </button>
                        </div>
  </div>
</nav>
    <!--<header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ASP</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item dropdown">

                                <a class="nav-link dropdown-toggle" href="#" id="routedropdown" role="button" data-bs-toggle="dropdown">
                                    Werknemer
                                </a>

                                <div class="dropdown-menu" aria-labelledby="routedropdown">
                                     <a class="dropdown-item" asp-controller="Werknemer" asp-action="WerknemerToevoegenView">Werknemer Toevoegen</a>
                                     <a class="dropdown-item" asp-controller="Werknemer" asp-action="WerknemerAanpassenView">Werknemer Aanpassen</a>
                                     <a class="dropdown-item" asp-controller="Werknemer" asp-action="WerknemerVerwijderenView">Werknemer Verwijderen</a>
                                </div>
                            </li>

                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="routedropdown" role="button" data-bs-toggle="dropdown">
                                    Route
                                </a>

                                <div class="dropdown-menu" aria-labelledby="routedropdown">
                                     <a class="dropdown-item" asp-controller="Route" asp-action="RouteToevoegenView">Route Toevoegen</a>
                                     <a class="dropdown-item" asp-controller="Route" asp-action="RouteAanpassenView">Route Aanpassen</a>
                                     <a class="dropdown-item" asp-controller="Route" asp-action="RouteVerwijderenView">Route Verwijderen</a>
                                </div>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Home" asp-action="MonthConclusion">Maand Gegevens</a>
                            </li>

                        </ul>
                        <button type="button" class="btn btn-outline-danger" onclick="logout()">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-box-arrow-right" viewBox="0 0 16 16">
                                <path fill-rule="evenodd" d="M10 12.5a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v2a.5.5 0 0 0 1 0v-2A1.5 1.5 0 0 0 9.5 2h-8A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-2a.5.5 0 0 0-1 0v2z"></path>
                                <path fill-rule="evenodd" d="M15.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 0 0-.708.708L14.293 7.5H5.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3z"></path>
                            </svg>
                            Log Out
                        </button>
                    </div>
            </div>
        </nav>
    </header>-->
    <div class="container">
        <main role="main" class="pb-3 mt-5">
            
            @RenderBody()
        </main>
    </div>

    <script type="text/javascript">
        function logout(){
            window.location.href = window.location.protocol + "//" + window.location.host;
        }
    </script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>